### ISSUE TITLE
Make user profile page

### ISSUE THREAD

**Issue by shivam1317** [KYogesh20/Chat-Society#42]
Currently when user clicks on profile icon they get logged out.
but now we have to make one profile page which will show their username, email and a logout button.
add route `/profile` to routes.

**Comment by tarunsamanta2k20** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by shivam1317** [comment]
hey  @tarunsamanta2k20,
Can you provide us any UI design or inspiration from where you are going to make the `profile` page so that we can confirm the final design.
also make sure that it matches the theme.
Thanks.
