### ISSUE TITLE
Change UI for Login and Register page

### ISSUE THREAD

**Issue by shivam1317** [KYogesh20/Chat-Society#43]
the current UI for `Login` and `Register` page is simple so we have to improve its design.
Also make sure that it matches the theme of `House` and `Chatrooms` if possible.

Current login page: https://chat-society2022.vercel.app/login
Current register page: https://chat-society2022.vercel.app/register

also there is one small change needed in current UI for both pages which is mentioned below:
Make separator for auth providers like this

![Image](https://user-images.githubusercontent.com/70281451/210397517-4cb884e9-ec3f-4e94-9e61-b89adf090e27.png)

**Comment by Adejuwon-00** [comment]
Can you provide more context as to what you mean?

**Comment by shivam1317** [comment]
hey @Adejuwon-00 ,
i have improved the message above.
hope it helps.

**Comment by Adejuwon-00** [comment]
Thank you @shivam1317. Can you add a link to the design for clarity?

**Comment by shivam1317** [comment]
hey @Adejuwon-00 ,
Currently we don't have any design for these pages so you are free to use your design creativity to make whole page.
Before starting implementing it, please show us the design which you are going to make so that we can finalise it.
thank you.
